---

# tasks file for osp.servers
- name: Create new server instances and attaches them a network and passes metadata to the instance
  os_server:
    cloud: ospcloud
    name: "{{ frontend.name }}"
    image: "{{ frontend.image }}"
    meta: "group={{ frontend.meta.group }},deployment_name={{ frontend.meta.deployment_name }}"
    flavor: "{{ frontend.flavor }}"
    security_groups: "{{ frontend.security_group }}"
    key_name: "{{ frontend.key_name}}"
    wait: yes
  register: frontend_instanceip

- name: Add floating IP to frontend Servers
  os_floating_ip:
    cloud: ospcloud
    state: present
    reuse: yes
    server: "{{ frontend.name }}"
    network: ext_network
    wait: true
    timeout: 180
  register: instancefloatingip
   
- name: Wait for server to be available
  wait_for:
    host: "{{ instancefloatingip.floating_ip.floating_ip_address }}"
    port: 22
    search_regex: OpenSSH
    timeout: 600
  delegate_to: "{{ inventory_hostname }}"
